[workspace]
resolver = "2"
members = [
    "server",
    "blocks",
    "blocks-macros",
    "blocks/native/hello",
    "blocks/native/liquid-dsp",
    "runtime",
]

[workspace.package]
edition      = "2021"
rust-version = "1.89"
license      = "GPL-3.0-or-later"
repository   = "https://github.com/sirmick/ferrite"
authors      = ["Mick <sirmick@gmail.com>"]

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
pedantic          = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc     = "allow"
missing_panics_doc     = "allow"

[profile.release]
lto           = "thin"
codegen-units = 1
